# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = "[](bold #cba6f7)  $directory [❯](bold #a6e3a1)[❯](bold #89b4fa)[❯](bold #fab387) "
right_format = "$git_branch"

# Inserts a blank line between shell prompts
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[❯](bold green)[❯](bold blue)[❯](bold orange)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
format = "[](bold #cba6f7) [❯](bold #89b4fa)[❯](bold #fab387) [$branch](bold #f5c2e7)"

[directory]
format = "[$path](#f5c2e7)"
