#!/bin/bash
if [ "$1" == "used" ]; then
  free --mebi | sed -n '2{p;q}' | awk '{printf ("%2.2fGB\n", ( $3 / 1024))}'
elif [ "$1" == "total" ]; then
  free --mebi | sed -n '2{p;q}' | awk '{printf ("%2.2fGB \n", ( $2 / 1024))}'
elif [ "$1" == "free" ]; then
  free --mebi | sed -n '2{p;q}' | awk '{printf ("%2.2fGB \n", ( $4 / 1024))}'
fi
