#!/bin/bash
workspaces() {
  ws1="1"
  ws2="2"
  ws3="3"
  ws4="4"
  ws5="5"
  ws6="6"
  ws7="7"

  # Unoccupied
  un="0"

  # check if Occupied
  o1=$(bspc query -D -d .occupied --names | grep "$ws1" )
  o2=$(bspc query -D -d .occupied --names | grep "$ws2" )
  o3=$(bspc query -D -d .occupied --names | grep "$ws3" )
  o4=$(bspc query -D -d .occupied --names | grep "$ws4" )
  o5=$(bspc query -D -d .occupied --names | grep "$ws5" )
  o6=$(bspc query -D -d .occupied --names | grep "$ws6" )
  o7=$(bspc query -D -d .occupied --names | grep "$ws7" )

  # check if Focused
  f1=$(bspc query -D -d focused --names | grep "$ws1" )
  f2=$(bspc query -D -d focused --names | grep "$ws2" )
  f3=$(bspc query -D -d focused --names | grep "$ws3" )
  f4=$(bspc query -D -d focused --names | grep "$ws4" )
  f5=$(bspc query -D -d focused --names | grep "$ws5" )
  f6=$(bspc query -D -d focused --names | grep "$ws6" )
  f7=$(bspc query -D -d focused --names | grep "$ws7" )

  ic_1="ﯶ" # nf-mdi-nut
  ic_2="ﯶ" # nf-mdi-nut
  ic_3="ﯶ" # nf-mdi-nut
  ic_4="ﯶ" # nf-mdi-nut
  ic_5="ﯶ" # nf-mdi-nut
  ic_6="ﯶ" # nf-mdi-nut
  ic_7="ﯶ" # nf-mdi-nut

  if [ $f1 ]; then
      ic_1="" # nf-fa-dot_circle_o
  elif [ $f2 ]; then
      ic_2="" # nf-fa-dot_circle_o
  elif [ $f3 ]; then
      ic_3="" # nf-fa-dot_circle_o
  elif [ $f4 ]; then
      ic_4="" # nf-fa-dot_circle_o
  elif [ $f5 ]; then
      ic_5="" # nf-fa-dot_circle_o
  elif [ $f6 ]; then
      ic_6="" # nf-fa-dot_circle_o
  elif [ $f7 ]; then
      ic_7="" # nf-fa-dot_circle_o
  fi

  code="(box :class \"works\" :spacing \"-1\" :orientation \"h\" :halign \"center\" :space-evenly \"true\" (button :onclick \"bspc desktop -f $ws1\"	:class \"$un$o1$f1\" :halign \"center\"	\"$ic_1\") (button :onclick \"bspc desktop -f $ws2\"	:class \"$un$o2$f2\" :halign \"center\" \"$ic_2\") (button :onclick \"bspc desktop -f $ws3\"	:class \"$un$o3$f3\" :halign \"center\" \"$ic_3\")(button :onclick \"bspc desktop -f $ws4\"	:class \"$un$o4$f4\" :halign \"center\" \"$ic_4\") (button :onclick \"bspc desktop -f $ws5\"	:class \"$un$o5$f5\" :halign \"center\" \"$ic_5\")  (button :onclick \"bspc desktop -f $ws6\"	:class \"$un$o6$f6\" :halign \"center\" \"$ic_6\")  (button :onclick \"bspc desktop -f $ws7\" :class \"$un$o7$f7\" :halign \"center\" \"$ic_7\"))"
  
  echo "$code"
}
workspaces
bspc subscribe all | while read -r _ ; do
workspaces
done

