#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 

xsetroot -cursor_name left_ptr

bspc config border_width         0
bspc config window_gap           5

bspc config left_padding         7
bspc config right_padding        7
bspc config bottom_padding       52 

#top padding
while true
do
  bspc config top_padding 7
  bspc config top_monocle_padding 7
done &

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config active_border_color     '#ddb6f2'
bspc config focused_border_color    '#ddb6f2'
bspc config normal_border_color     '#ffc47a'
bspc config presel_border_color     '#96cdfb'
bspc config urgent_border_color     '#f28fad'

bspc config active_locked_border_color      '#ddb6f2'
bspc config focused_locked_border_color     '#ffc47a'
bspc config normal_locked_border_color      '#96cdfb'

bspc config pointer_modifier        Mod4
bspc config pointer_action1         move
bspc config pointer_action2         resize_side
bspc config pointer_action2         resize_corner

bspc rule -a firefox desktop='^1'
bspc rule -a discord desktop='^2'
bspc rule -a spotify desktop='^4'
bspc rule -a code desktop='^5'
bspc rule -a supertuxkart state='tiling' desktop='^6'

bash ~/.config/autostart
