#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7

xsetroot -cursor_name left_ptr

bspc config border_width         0
bspc config window_gap           5

bspc config left_padding         7
bspc config right_padding        7
bspc config bottom_padding       80 
bspc config top_padding          7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config active_border_color     '#94f7c5'
bspc config focused_border_color    '#94f7c5'
bspc config normal_border_color     '#8cc1ff'

bspc config pointer_modifier        control
bspc config pointer_action1         move
bspc config pointer_action2         resize_side
bspc config pointer_action2         resize_corner

bspc rule -a firefox desktop='^1'
bspc rule -a discord desktop='^2'
bspc rule -a Spotify desktop='^4'
bspc rule -a code desktop='^5'
bspc rule -a Soundux desktop='^5'
bspc rule -a supertuxkart state='tiling' desktop='^6'
bspc rule -a eww-music state='floating'
bspc rule -a eww-user state='floating'
bspc rule -a eww-timedate state='floating'
bspc rule -a Pavucontrol state='floating'
bpsc rule -a carla desktop='^7'
bspc rule -a Carla1 desktop='^7'
bspc rule -a Carla2 desktop='^7'
bspc rule -a fsthost64 desktop='^7'
bspc rule -a Fsthost64 desktop='^7'
bspc rule -a qjackctl desktop='^7'
bspc rule -a QjackCtl desktop='^7'

/usr/lib/xfce-polkit/xfce-polkit &
~/.config/bspwm/scripts/eww-fullscreen-fix.sh &
eww daemon &
eww open bar &
picom &
dunst &
nitrogen --restore &
firefox &
export _JAVA_AWT_NONREPARENTING=1
